# This is not actually being used, just set up to get pickle working properly
base: &base
  adapter: postgresql

development:
  database: salesflip_dev
  <<: *base

test:
  database: salesflip_test
  <<: *base
