# This is not actually being used, just set up to get pickle working properly
base: &base
  adapter: postgres
  port: 5432
  pool: 5
  timeout: 5000

development:
  database: salesflip_development
  <<: *base

test:
  database: salesflip_test
  <<: *base

cucumber:
  database: db/lean_crm_cucumber.sqlite3
  <<: *base

staging:
  database: salesflip_staging
  user: postgres
  password: <%= ENV['SALESFLIP_POSTGRES_PASSWORD'] %>
  host: <%= ENV['SALESFLIP_POSTGRES_HOST'] %>
  <<: *base

production:
  database: salesflip_production
  user: postgres
  password: <%= ENV['SALESFLIP_POSTGRES_PASSWORD'] %>
  host: <%= ENV['SALESFLIP_POSTGRES_HOST' %>
  <<: *base
