# This is not actually being used, just set up to get pickle working properly
base: &base
  adapter: postgres
  pool: 5
  timeout: 5000

development:
  database: salesflip_development
  <<: *base

test:
  database: salesflip_test
  <<: *base

cucumber:
  database: db/lean_crm_cucumber.sqlite3
  <<: *base

production:
  database: db/salesflip_production.sqlite3
  <<: *base
