defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  use_object_ids: true

development:
  <<: *defaults
  database: salesflip_development

test:
  <<: *defaults
  database: salesflip_test

cucumber:
  <<: *defaults
  database: salesflip_cucumber

staging:
  <<: *defaults
  database: salesflip_staging
  host: <%= ENV['MONGODB_HOST'] %>
  port: <%= ENV['MONGODB_STAGING_PORT'] %>
  username: <%= ENV['MONGODB_STAGING_USER'] %>
  password: <%= ENV['MONGODB_STAGING_PASSWORD'] %>

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= ENV['MONGODB_HOST'] %>
  port: <%= ENV['MONGODB_PORT'] %>
  username: <%= ENV['MONGODB_USER'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
  database: salesflip
